let num;
document.write("Value after variable declaration is " + num);
let num1 = 5;
document.write("<br>Initial value: " + num1);
document.write("<br>Value after increment is: " + ++num1);
num1 += 7;
document.write("<br>Value after addition is: " + num1 );
document.write("<br>Value after decrement is: " + --num1);
let remainder = num1 % 3;
document.write("<br>The remainder is : " + remainder);